JWK_BuildItemsConfig {
 m_aBuildItems {
  JWK_BuildItemConfig "{68B97374C3312B36}" {
   m_sName "FFA_ArsenalFOB"
   m_sTitle "Equipment Arsenal"
   m_sDescription "Allow you to store loot stolen from the occupiers"
   m_tPreview "{5E520E847D6E4F91}UI/Textures/EditorPreviews/Auto/Compositions/Slotted/SlotFlatSmall/E_AmmoStorage_S_FIA_01.edds"
   m_iCost 0
   m_iSuppliesCost 500
   m_aPrefabs {
    "{EB0CB31A87C56CB0}Prefabs/Compositions/BuildItems/FOB_ArsenalStore.et"
   }
   m_iMaxBuiltPerArea 1
   m_iBuildAreaTypes 3
  }
 }
}