JWK_UIManagerConfig {
 m_aContexts {
  FFA_ArsenalContext "{68C200B15611E317}" {
   m_Layout "{EE9D1986B0307FAB}UI/Layouts/Menu/ArsenalMenu.layout"
   m_sInputContextName "FFA_ArsenalContext"
   m_bShowHintsOnTop 1
  }
 }
}