SCR_NotificationConfig {
 m_aNotificationDisplayData {
  SCR_NotificationNumber "{665AC4A56553585B}" {
   m_info SCR_UINotificationInfo "{665AC4A4149065AF}" {
    Name "Could not load %1 item(s). "
   }
  }
 }
}