ActionManager {
 Contexts {
  ActionContext FFA_ArsenalContext {
   Priority 50
   Flags 0x4 0
   Actions {
    Action JWK_ShopLoadout {
     Type Digital
     InputSource InputSourceSum "{68CD1C75EC3C9D7E}" {
      Sources {
       InputSourceValue "{68CD1C75EC3FFD7B}" {
        Input "keyboard:KC_TAB"
        Filter InputFilterClick "{68CD1C75EC3FFD4B}" {
        }
       }
       InputSourceValue "{68CD1C75EC3FFD57}" {
        Input "gamepad0:y"
        Filter InputFilterClick "{68CD1C75EC3FFD51}" {
        }
       }
      }
     }
    }
   }
   ActionRefs {
    "JWK_ShopTrade"
    "MenuNavLeft"
    "MenuNavRight"
    "MenuBack"
    "MenuSelect"
    "MenuLeft"
    "MenuRight"
    "MenuUp"
    "MenuDown"
    "MenuTabLeft"
    "MenuTabRight"
   }
  }
 }
}